### PR TITLE
Xor bitset

### PR DESCRIPTION
**Pull request by Aceeri**
Fixed the previous issues with it, just composes the bitset from other bitsetlikes.

### CODE REVIEW

**Review by WaDelma — CHANGES_REQUESTED** [review]
Looking good, but there are not tests for it.

**Review by torkleyy — APPROVED** [review]
LGTM

**Comment by torkleyy** [comment]
Thanks!

bors r+

**Comment by kvark** [comment]
We need some tests here!

**Comment by torkleyy** [comment]
@kvark Yes, requested in the other PR.

**Review by kvark — COMMENTED** [review]
TBH, I don't think this implementation is useful. Every layer has to re-calculate the same expression:
```rust
let xor = BitSetAnd(BitSetOr(&self.0, &self.1), BitSetNot(BitSetAnd(&self.0, &self.1)));
```
So doing any sort of checks, which means traversing the layers, would do redundant work. Alternatively, the user can do this expression once on their side and re-use it. If we want to make it work, we could consider hiding the members and pre-computing the XOR expression in the constructor or something...

**Comment by torkleyy** [comment]
You're right, I don't know why I missed that. @Aceeri Please address that in the other PR.

**Comment by torkleyy** [comment]
Actually, there's no calculation involved. @kvark

**Comment by kvark** [comment]
hmm, indeed this is just constructed. Sorry about the false alarm then :)
@Aceeri 👍

**Pull request merged**
