### PR TITLE
Add operators for references to bitsets

### PR DESCRIPTION
**Pull request by Aceeri**
Forgot to include this in my previous PR.

### CODE REVIEW

**Comment by kvark** [comment]
looks fine to me, as long as we can still tell for sure which of the operator functions is called at any place

**Review by torkleyy — COMMENTED** [review]
Maybe we could add some tests to make sure operations aren't ambiguous?

**Comment by torkleyy** [comment]
Please add xor and tests as requested by @WaDelma, then merge.

bors delegate=@Aceeri

**Pull request merged**
