### PR TITLE
Add XOR operation to bitsets

### PR DESCRIPTION
**Pull request by Aceeri**

### CODE REVIEW

**Review by kvark — CHANGES_REQUESTED** [review]
This is not going to work straight like this. Layer has 1 where there are any bits underneath that are 1.
Thus, consider bits A and B on the same layer of different bitsets. Supposing (A = 0 | 1) and (B = 1 | 0). Xorring them would give you C = A ^ B = 0, while what you actually want to get is still "1" because the XOR of underlying bits would give you (1 | 1).

**Comment by Aceeri** [comment]
Ah true, wrote this very quickly last night when I had other ideas in my head... hmm.

**Comment by Aceeri** [comment]
Ignore this PR for now, need to fix some things.

**Comment by Aceeri** [comment]
Going to close this for now because it is a somewhat complex issue.

**Pull request closed without merging**
