### PR TITLE
Push to 1.0

### PR DESCRIPTION
**Pull request by Xaeroxe**
This crate has been stable for a pretty long time. I think it's time to make it 1.0

### CODE REVIEW

**Comment by kvark** [comment]
What would this version change give you?

**Comment by Xaeroxe** [comment]
A signal to users that this is considered complete and production ready.

**Comment by kvark** [comment]
It's only really used by Specs/Amethyst and Wyrm. Both are not production ready and not nearly tested enough to be considered stable. It doesn't appear to me that there is a line of stakeholders waiting for hibitset to be stabilized. Rather, there is a few experimental projects that depend on it, and they need more test coverage so that the dependencies are tested, before we can call it production ready.

**Comment by Xaeroxe** [comment]
It seems unfair to me to require downstream users to be 1.0 before this can be 1.0. However for what it's worth Amethyst is quite happy with this crate. We've got a lot of work that needs to be done but this crate in particular has seen a lot of use and we do have several unit tests that verify it works correctly.

**Comment by Xaeroxe** [comment]
The other thing I'd like to make clear is 1.0 isn't the last version, it's just the first version at which point we're guaranteeing we're going to uphold semver.

**Comment by torkleyy** [comment]
@kvark I think the primary motivation for this change is that we want to stabilize Specs.

@Xaeroxe I don't think we should release a 1.0 yet. Let's do shred and hibitset releases together with Specs 1.0, and after some more future proofing of the API.

**Comment by kvark** [comment]
How does specs stabilization require hibitset to be 1.0?

**Comment by torkleyy** [comment]
@kvark it's a public dependency, used in almost every crate depending on Specs. Public dependencies of 1.0 crates have to be >= 1.0.

**Comment by kvark** [comment]
@torkleyy I forgot that it's public. You'd think that all the user really needs is a bitset, which has a pretty small and stable API, and hierarchical bitset is just an implementation of it. So technically it could be the implementation detail of Specs and a private dependency.

That is to say, I don't have a stake in the ground here. I don't mind it to be 1.0 if you need it, and I don't think I even have enough information to make judgement on how stable it is.

**Comment by Xaeroxe** [comment]
Has merge conflicts and is a trivial PR. Closing.

**Pull request closed without merging**
